application: weihwa-puzzles
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images

- url: /staticgadgets
  static_dir: staticgadgets

- url: /staticjs
  static_dir: staticjs

- url: /.*
  script: mainpage.py
