application: weihwa-puzzles
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images
  expiration: 8d 8h

- url: /js/puzzle-utils6\.js
  script: mainpage.py

- url: /js/puzzle-utils7\.js
  script: mainpage.py

- url: /js
  static_dir: staticjs
  expiration: 1d

- url: /gadgets/20080523-diagonalsudoku.xml
  script: mainpage.py

- url: /gadgets/test-auth.xml
  script: mainpage.py

- url: /gadgets/testsol.xml
  script: mainpage.py

- url: /gadgets
  static_dir: staticgadgets

- url: /staticgadgets
  static_dir: staticgadgets

- url: /.*
  script: mainpage.py
